# Generated by Django 5.1.3 on 2024-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
