# Generated by Django 5.1.4 on 2024-12-10 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid street address (number followed by street name)', regex='^[0-9]+\\s+[A-Za-z0-9\\s.,\\-#/]+$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
