# Generated by Django 5.1.4 on 2024-12-11 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phonenumber', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 9-14 digits.', regex='^\\+?1?\\d{9,14}$')])),
                ('emails', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('address', models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid street address (number followed by street name)', regex='^[0-9]+\\s+[A-Za-z0-9\\s.,\\-#/]+$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
