# Generated by Django 5.1.3 on 2024-12-06 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_Option', models.CharField(max_length=10)),
                ('Parent_Name', models.CharField(max_length=30)),
                ('Pet_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=13)),
                ('Alternate_Phone', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=500)),
                ('Pet_Breed', models.CharField(max_length=70)),
                ('Pet_DOB', models.CharField(max_length=12)),
                ('Pet_checkIn', models.CharField(max_length=12)),
                ('Pet_checkOut', models.CharField(max_length=12)),
                ('Pet_FeedingInfo', models.CharField(max_length=200)),
                ('Pet_Size', models.CharField(max_length=20)),
                ('Pet_Behaviour', models.CharField(max_length=15)),
                ('Pet_Grooming', models.CharField(max_length=25)),
                ('Special_instruction', models.CharField(max_length=500)),
                ('aggrement', models.CharField(max_length=10)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('boarding_status', models.CharField(max_length=10)),
                ('state_of_board', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
        migrations.CreateModel(
            name='callus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Customer_Name', models.CharField(max_length=40)),
                ('phone_Number', models.CharField(max_length=13)),
                ('enquiry', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'callus',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Customer_Name', models.CharField(max_length=40)),
                ('phone_Number', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='cust_vet_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Parent_Name', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=13)),
                ('Scheduled_date', models.CharField(max_length=12)),
                ('Scheduled_time', models.CharField(max_length=10)),
                ('service_choosen', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cust_vet_schedule',
            },
        ),migrations.CreateModel(
            name='pet_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.BigIntegerField()),
                ('Pet_Name', models.CharField(max_length=30)),
                ('Parent_Name', models.CharField(max_length=30)),
                ('Pet_Breed', models.CharField(max_length=20)),
                ('Advance_Payment', models.BigIntegerField(default=0)),
                ('Balance_Payment', models.BigIntegerField(default=0)),
                ('Total_Payment', models.BigIntegerField(default=0)),
                ('per_day_charge', models.BigIntegerField(default=0)),
                ('PnD_service_charge', models.BigIntegerField(default=0)),
                ('grooming_charge', models.BigIntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pet_payments',
            },
        ),
        migrations.CreateModel(
            name='pet_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Pet_Type', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'pet_types',
            },
        ),
        migrations.CreateModel(
            name='vet_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Parent_Name', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=13)),
                ('Scheduled_date', models.CharField(max_length=12)),
                ('Scheduled_time', models.CharField(max_length=10)),
                ('service_choosen', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vet_check',
            },
        ),
    ]
