# Generated by Django 5.1.3 on 2024-12-06 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 9-14 digits.', regex='^\\+?1?\\d{9,14}$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('message', models.TextField(validators=[django.core.validators.RegexValidator(message='Message must be between 10 and 1000 characters.', regex='^.{10,1000}$')])),
            ],
            options={
                'db_table': 'partnership',
            },
        ),
    ]
