# Generated by Django 5.1.3 on 2024-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petService', '0002_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
